#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jun  9 10:28:49 2020

@author: peter
"""

import numpy as np
import matplotlib.pyplot as plt
import FRI_functions as FRIF
import scipy.signal
import scipy.linalg
import scipy.special
import scipy.io


c_m_n_input = scipy.io.loadmat('./data/c_m_n_input.mat')
c_m_n = FRIF.get_c_mn_exp2(np.squeeze(c_m_n_input['alpha_vec']),np.squeeze(c_m_n_input['n_vec']),np.squeeze(c_m_n_input['psi']),np.squeeze(c_m_n_input['t_psi']))

test_dict = scipy.io.loadmat('./data/input_extract_decaying.mat')
c_m_n_test = np.squeeze(test_dict['c_m_n'])

np.testing.assert_allclose(c_m_n,c_m_n_test)